# Conversions

## TF2SS

In [7]:
import numpy as np
import sympy 
sympy.init_printing()
print('sympy version '+sympy.__version__)

s = sympy.Symbol('s')

from control.matlab import *

def near_zero(P):
    for ii in range(len(P.num[0][0][:])):
        if abs(P.num[0][0][ii]) < 1e-12:
            P.num[0][0][ii] = 0
        else:
            P.num[0][0][ii] = P.num[0][0][ii]
    return P

sympy version 1.9


In [8]:
s = tf('s')
P = 4/(s**3 + 2*s**2 + 3*s + 4)
P

TransferFunction(array([4]), array([1, 2, 3, 4]))

In [10]:
sys = tf2ss(P)
print('A = \n',sys.A)
print('B = \n',sys.B)
print('C = \n',sys.C)
print('D = \n',sys.D)

A = 
 [[-2. -3. -4.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]]
B = 
 [[1.]
 [0.]
 [0.]]
C = 
 [[0. 0. 4.]]
D = 
 [[0.]]


## SS2TF

In [11]:
PP = ss2tf(sys)
PP = near_zero(PP)

In [12]:

PP

TransferFunction(array([0., 0., 4.]), array([1., 2., 3., 4.]))