# Unified Engineering<br> 16.002 Signals and Systems<br> Algebra Review
## Jonathan P. How <br> Massachusetts Institute of Technology<br> jhow@mit.edu

In [45]:
import cmath as cm
import numpy as np
import pandas as pd

**Contents:** <pre> 
[Key Components](#s1)  
[Special Matrices](#s2)  
[Matrix Operations](#s3)  
[More Complex Operations](#s4)  
 </pre>

## <a name="s1" style="color:blue">Key Components</a>

### Scalars
A $1\times 1$ matrix is called a *scalar*. In other words, a scalar is just a number. 

### Matrices
A <a style="color:blue">*matrix*</a> is a (two-dimensional or rectangular) array of numbers. The size of a matrix is represented in the form $m \times n$, where $m$ is the number of rows and $n$ is the number of columns. 

For example, the following is an example of a $3 \times 5$ matrix:
\begin{equation}
M=\left[\begin{array}{c c c c c} 1 & 2.5 & 3.76 & -2.3 & 4.1 \\ 0.78 & -6.2 & -3.5 & 4.5 & 3 \\ 1 & 2 & 3 & 4 & 5 \end{array}  \right]
\end{equation}
If $m=n$, the matrix is said to be *square*. The elements of the matrix are denoted by $a_{ij}$, where $i$ denotes the row and $j$ the column of the element. In the above example, $m_{23} = -3.5$. 

### Vectors
A matrix with only one row or column (preferred), that is, an $n \times 1$ matrix, is known as a <a style="color:blue">*vector*</a>.
When there is one column, the number of rows is sometimes called the *dimension* of the vector. 

## <a name="s2" style="color:blue">Special matrices</a>
This section considers some special instances of matrices.

### Zero matrix
A matrix with all elements equal to zero is called a *zero matrix*. 
Often, an $m \times n$ zero matrix is denoted by $0_{m\times n}$, but sometimes it is just represented by $0$ and we will deduce its size by context. 

### Identity matrix
A square matrix with all diagonal elements equal to 1, and all other elements equal to 0, is known as the *identity matrix*. They are usually denoted by $I$, although we will sometimes use $I_m$ or $I_{m \times m}$ to denote the $m \times m$ identity matrix. For example, 
\begin{equation}
I_3 = \left[\begin{array}{c c c} 1 & 0  & 0 \\ 0 & 1 & 0 \\  0 & 0 &1 \end{array}  \right] \mbox{ and } I_4 = \left[\begin{array}{cccc} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \end{array} \right] \end{equation} 
are identity matrices. When we look at matrix multiplication, we will see why such a matrix is called an identity matrix.

### Unit vector
If only one component of a vector is equal to 1 and all the other elements are 0, it is known as a *unit vector*. The unit vector in which the $i$th element is 1 is sometimes denoted $e_i$. For example,
\begin{equation} e_1 =  \left[\begin{array}{c} 1 \\ 0 \\ \vdots \\ 0 \end{array}  \right],\; 
e_2 =  \left[\begin{array}{c} 0 \\ 1 \\ \vdots \\ 0 \end{array}   \right],\mbox{ etc.} 
\end{equation} 
The unit vector $e_i$ is sometimes known as the $i$th basis vector. Also note that
$$
I_3=\left[ \begin{array}{ccc} e_1 & e_2 & e_3 \end{array}\right]
$$

### Vector of ones 
A vector in which all the elements equal 1 is sometimes called the *ones vector* and denoted $\mathbf{1}$. 

## <a name="s3" style="color:blue">Matrix operations</a>

### Addition
If $A$ and $B$ are two matrices *of the same dimension*, they can be added to obtain a matrix with the same dimensions. In other words,
$$ C = A+B, \mbox{ whose elements are given by }  c_{ij} = a_{ij} + b_{ij}. $$
Adding the zero matrix (of the same size) to any matrix yields the same matrix.

### Transpose
The transpose of a matrix, denoted $A^T$, is obtained by interchanging the rows and the columns, so
$$
(A^T)_{ij}=a_{ji}.
$$
The transpose of a *symmetric matrix* is the matrix itself -- in fact, if $A=A^T$, then $A$ is symmetric.

### Trace 
The trace of a square matrix is the sum of its diagonal elements, so 
$$
Tr(A) = \sum_{i=1}^n a_{ii}.
$$

### Multiplication
Two matrices $A$ and $B$  can only be multiplied if their dimensions are *compatible*, that is, if the number of columns of $A$ equals the number of rows of $B$. If $A$ is $m\times n$ and $B$ is $n\times p$, then the product  $C=AB$ is a $m \times p$ matrix. The element $c_{ij}$ of the product is given by
$$c_{ij} = \sum_{k=1}^n a_{ik} b_{kj} = a_{i1}b_{1j} + a_{i2}b_{2j} + a_{i3}b_{3j} + \cdots + a_{in}b_{nj}. $$

Note that matrix multiplication is **not** commutative. In fact, depending on the sizes of the matrices, the product $BA$ may not even make sense. Even if $m=p$ above (and therefore $BA$ exists), $AB \neq BA$ in general.  

However, suppose $B = I_{n \times n}$, the appropriately-sized identity matrix. Then, we note that $A I_{n \times n} = A$ and $I_{m \times m} A = A$. In other words, the identity matrix is the multiplicative identity, hence its name.

### Inner product of vectors
If $u$ and $v$ are $n \times 1$ column vectors, their product $u^Tv$ is a $1\times 1$ matrix, namely, a scalar.  This product is known as the *inner product* or *dot product* of the two vectors:
$$ \langle u,v \rangle = u \cdot v = u^Tv = u_1v_1 + u_2v_2 + \cdots + u_nv_n.  $$
We see that the inner product of a vector with itself is given by 
$$ u^T u = u_1^2 + u_2^2 + \cdots + u_n^2. $$

## <a name="s4" style="color:blue">More Complicated Operations</a>
### Norm of a vector
The *norm of a vector* $u$ is a measure of its size or magnitude.  It is a non-negative scalar quantity $|u|$ such that:
- $\|u\| >0 \mbox{ when }  u \ne 0$ and $|u\|=0 \mbox{ if and only if } u = 0$ 
- $\|ku\| = |k| \|u\| \mbox{ for any scalar } k$; and 
- $ \|u+v\| \le \|u\| + \|v\|$.

A commonly used vector norm, known as the $L_2$ norm, is the square root of its inner product with itself:
$$ \|u\| = \|u\|_2 = (u^T u)^{1/2} = \sqrt{u_1^2 + u_2^2 + \cdots + u_n^2}.$$

### Determinant
The determinant of a *square* matrix $A$ is given by 
$$ \mbox{det}(A) = \sum_{j=1}^n a_{ij}\gamma_{ij}, \mbox{ for any } i = 1,\cdots, n, $$ 
where $\gamma_{ij} = (-1)^{i+j}\mbox{det}(M_{ij})$ is called a \textit{cofactor} and $M_{ij}$ is called a \textit{minor}. A minor $M_{ij}$  is matrix $A$ with  its $i$th row and $j$th column removed. 
%
The *adjugate} of a matrix, adj$(A)$ is the transpose of the matrix of its cofactors. In other words, $\mathrm{adj}(A) = [\gamma_{ij}]^T$.  
- The determinant of a $2 \times 2$ matrix is given by $a_{11}a_{22} - a_{21}a_{12}$. 
- The determinant of a $3 \times 3$ matrix is given by\\
 $a_{11}a_{22}a_{33}-a_{11}a_{23}a_{32}-a_{12}a_{21}a_{33}+a_{12}a_{23}a_{31}+a_{13}a_{21}a_{32}-a_{13}a_{22}a_{31}$.

### Inverse
The inverse of a square matrix A, denoted $A^{-1}$, is one that satisfies the property 
$$ A^{-1}A = AA^{-1} = I.$$
It can also be shown that $$ A^{-1} = \frac{\mathrm{adj}(A)}{\mathrm{det}(A)}$$ 
where *adj* refers to the <a href="https://en.wikipedia.org/wiki/Adjugate_matrix">
adjoint</a> of a matrix.

The above implies that a matrix has an inverse if  its determinant is non-zero. Such a matrix is said to be *nonsingular* or *invertible*.

The inverse of a $2 \times 2$ invertible matrix is given by
$$ A^{-1}=\frac{1}{a_{11}a_{22} - a_{12}a_{21}} \left[ \begin{array}{cc} a_{22} & -a_{12} \\ -a_{21} & a_{11} \end{array}\right]. $$

## Eigenvalues and Eigenvectors
An <a style="color:red">eigenvalue</a> of a square matrix $A$ is any scalar $\lambda$ that satisfies the equation $$Av = \lambda v.$$ The corresponding vector $v$ is known as an <a style="color:red">eigenvector</a> of the matrix. Rearranging the terms gives
$$(\lambda I-A)v = 0.$$

Since $v \ne 0$, we get
$$ \mathrm{det}(\lambda I - A) = 0,$$
where the lefthand side is known as the characteristic polynomial of $A$. In other words, the eigenvalues of a matrix are the roots of its characteristic polynomial. 

### <a style="color:blue">Numerical Examples</a>

In [48]:
A = np.array([[1,2,3],[2,5,2],[1,1,1]])
eigval,eigvec = np.linalg.eig(A)
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
print("Eigenvalues:",eigval)
print("Eigenvectors:\n",eigvec)

detA = []
for ii in range(3):
    detA.append(np.linalg.det(A-eigval[ii]*np.diag([1,1,1])))
print("\nIs zero? "+', '.join('{:0.3e}'.format(i) for i in detA))

Eigenvalues: [ 6.555 -0.760  1.205]
Eigenvectors:
 [[-0.439 -0.895  0.679]
 [-0.867  0.167 -0.589]
 [-0.235  0.414  0.439]]

Is zero? -6.710e-15, 5.450e-15, -3.182e-15


## Solving systems of linear equations
Simultaneous linear equations can be represented in terms of a matrix equation. For example, 
\begin{equation}
\begin{array}{ccccccc} x &+& 2y &+& 3z &=& 1 \\  2x &+& 5y &+& 2z &=& 2 \\ x &+& y &+& z &=& 3 \end{array}  
\end{equation}

\begin{equation}
\Longrightarrow \left[\begin{array}{ccc} 1 & 2 & 3 \\  2 & 5 & 2 \\ 1 & 1 &1 \end{array}\right]  \left[\begin{array}{c} x \\ y \\ z  \end{array}\right] =  \left[\begin{array}{c} 1 \\ 2 \\ 3  \end{array}\right].
\end{equation}
Given the linear system of equations that is written in the form $Ax = b$, the solution can be written as 
$$ x = A^{-1} b, $$
as long as $A$ is invertible. (*If $A$ is not invertible, the set of equations is either inconsistent or redundant.*) 

$$\left[\begin{array}{c} x \\ y \\ z  \end{array}\right] =  \left[\begin{array}{ccc} 1 & 2 & 3 \\  2 & 5 & 2 \\ 1 & 1 &1 \end{array}\right]^{-1}\left[\begin{array}{c} 1 \\ 2 \\ 3  \end{array}\right]  =  \left[\begin{array}{r} \frac{14}{3} \\ -\frac{4}{3} \\ -\frac{1}{3}  \end{array}\right].  $$

Systems of simultaneous equations can also be solved using the <a href="https://en.wikipedia.org/wiki/Gaussian_elimination"> Gaussian elimination of variables</a> or 
<a href="https://en.wikipedia.org/wiki/Cramer%27s_rule"> Cramer's rule.</a>

### <a style="color:blue">Numerical Examples</a>

In [47]:
A = np.array([[1,2,3],[2,5,2],[1,1,1]])
b = np.array([1,2,3])
sol = np.linalg.inv(A)@b
print(sol*3)

[ 14.000 -4.000 -1.000]
